version: "3"
services:
    db:
        image: postgres:latest
        restart: always
        ports:
            - "5433:5432"
        environment:
            POSTGRES_USER: "stock-sell-app"
            POSTGRES_PASSWORD: "password123"
        volumes:
            - ./data:/var/lib/postgresql/data