[build]
command = "npm run prisma:generate && npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[context.production.environment]
NEXTAUTH_URL = "https://stock-sell-web-98f6dd.netlify.app"
NEXTAUTH_SECRET = "nextAuthSecret"

[[redirects]]
  from = "/api/auth/*"
  to = "/api/auth"
  status = 200

[[headers]]
  # Match all headers for the main domain.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  # Enable cache control for static files.
  for = "/*.js"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Disable cache for dynamic content.
  for = "/api/auth/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"