import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import getCurrentUser from '@/app/actions/getCurrentUser'
import dynamic from 'next/dynamic'

import Providers from '@/providers';
import ToastProvider from '@/components/ToastProvider'
import { User } from '@prisma/client'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Navbar = dynamic(() => import('@/components/Navbar'), { ssr: false });

export default async function RootLayout({
  children,
  currentUser
}: {
  children: React.ReactNode,
  currentUser: User | null
}) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <Providers>
          <Navbar currentUser={currentUser} />
          <ToastProvider />
          {children}
        </Providers>
      </body>
    </html>
  )
}

// getServerSideProps 함수 정의
export async function getServerSideProps() {
  // 서버 측에서 currentUser 데이터 가져오기
  const currentUser = await getCurrentUser();

  // 가져온 currentUser를 props로 반환
  return {
    props: {
      currentUser
    }
  }
}